title: CIPH3R Sensitive Data Extraction
type: community
group: Natural Language Processing
order: 1
image: /static/templates/named-entity-recognition.png
details: <h1>Extract sensitive data using CIPH3R</h1>
config: |
  <View>
    <Labels name="label" toName="text">
        <Label value="PERSON" description="Person names"/>
        <Label value="US_DRIVER_LICENSE" description="US driver license numbers"/>
        <Label value="EMAIL_ADDRESS" description="Email addresses"/>
        <Label value="CREDIT_CARD" description="Credit card numbers"/>
        <Label value="CRYPTO" description="Cryptocurrency addresses"/>
        <Label value="IBAN_CODE" description="IBAN codes"/>
        <Label value="IP_ADDRESS" description="IP addresses"/>
        <Label value="MEDICAL_LICENSE" description="Medical license numbers"/>
        <Label value="US_BANK_NUMBER" description="US bank account numbers"/>
        <Label value="US_ITIN" description="US ITIN numbers"/>
        <Label value="US_SSN" description="US SSN numbers"/>
        <Label value="US_PASSPORT" description="US passport numbers"/>
        <Label value="LOCATION" description="Location names"/>
        <Label value="ORGANIZATION" description="Organization names"/>
        <Label value="DATE_TIME" description="Date and time"/>
        <Label value="PHONE_NUMBER" description="Phone numbers"/>
        <Label value="NRP" description="NRP numbers"/>
        <Label value="URL" description="URLs"/>
        <Label value="ACCOUNT_NUMBER" description="Account numbers"/>
        <Label value="HEALTH_INSURANCE_ID_NUMBER" description="Health insurance ID numbers"/>
        <Label value="MEDICATION" description="Medication names"/>
        <Label value="MEDICAL_CONDITION" description="Medical conditions"/>
        <Label value="USERNAME" description="Usernames"/>
        <Label value="REGISTRATION_NUMBER" description="Registration numbers"/>
        <Label value="STUDENT_ID_NUMBER" description="Student ID numbers"/>
        <Label value="FLIGHT_NUMBER" description="Flight numbers"/>
        <Label value="BLOOD_TYPE" description="Blood types"/>
        <Label value="CVV" description="CVV numbers"/>
        <Label value="CVC" description="CVC numbers"/>
        <Label value="RESERVATION_NUMBER" description="Reservation numbers"/>
        <Label value="SOCIAL_MEDIA_HANDLE" description="Social media handles"/>
        <Label value="LICENSE_PLATE_NUMBER" description="License plate numbers"/>
        <Label value="POSTAL_CODE" description="Postal codes"/>
        <Label value="SERIAL_NUMBER" description="Serial numbers"/>
        <Label value="VEHICLE_REGISTRATION_NUMBER" description="Vehicle registration numbers"/>
        <Label value="CREDIT_CARD_BRAND" description="Credit card brands"/>
        <Label value="VISA_NUMBER" description="Visa numbers"/>
        <Label value="INSURANCE_COMPANY" description="Insurance company names"/>
        <Label value="IDENTITY_DOCUMENT_NUMBER" description="Identity document numbers"/>
        <Label value="TRANSACTION_NUMBER" description="Transaction numbers"/>
        <Label value="BIRTH_CERTIFICATE_NUMBER" description="Birth certificate numbers"/>
        <Label value="TRAIN_TICKET_NUMBER" description="Train ticket numbers"/>
        <Label value="FLIGHT_BOOKING_NUMBER" description="Flight booking numbers"/>
        <Label value="MEDICAL_RECORD_NUMBER" description="Medical record numbers"/>
        <Label value="VEHICLE_IDENTIFICATION_NUMBER" description="Vehicle identification numbers"/>
        <Label value="ADDRESS" description="Addresses"/>
        <Label value="ALLERGIES" description="Allergies"/>
        <Label value="SURGICAL_HISTORY" description="Surgical history"/>
        <Label value="PATIENT_ID" description="Patient ID numbers"/>
        <Label value="PROVIDER_ID" description="Provider ID numbers"/>
        <Label value="DOB" description="Date of birth"/>
    </Labels>
    

    <Text name="text" value="$text"/>
  </View>

